# Generated by Django 3.2 on 2023-08-13 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10, 'Значение не может быть выше 10'), django.core.validators.MinValueValidator(1, 'Значение не может быть меньше 1')], verbose_name='Оценка'),
        ),
    ]
