# Generated by Django 3.2 on 2023-08-14 19:56

import django.core.validators
from django.db import migrations, models
import re
import reviews.validators


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0003_alter_review_score"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("id",),
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={
                "ordering": ("id",),
                "verbose_name": "Жанр",
                "verbose_name_plural": "Жанры",
            },
        ),
        migrations.AlterModelOptions(
            name="review",
            options={
                "ordering": ("pub_date",),
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
            },
        ),
        migrations.AlterModelOptions(
            name="title",
            options={
                "ordering": ("id",),
                "verbose_name": "Произведение",
                "verbose_name_plural": "Произведения",
            },
        ),
        migrations.AlterModelOptions(
            name="сomment",
            options={
                "ordering": ("pub_date",),
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-a-zA-Z0-9_]+\\Z"),
                        "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                        "invalid",
                    )
                ],
                verbose_name="URL",
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="slug",
            field=models.SlugField(
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-a-zA-Z0-9_]+\\Z"),
                        "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                        "invalid",
                    )
                ],
                verbose_name="URL",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="score",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(
                        10, "Значение должно быть до 10"
                    ),
                    django.core.validators.MinValueValidator(
                        1, "Значение должно быть от 1"
                    ),
                ],
                verbose_name="Оценка",
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="year",
            field=models.PositiveIntegerField(
                db_index=True, validators=[reviews.validators.validate_year]
            ),
        ),
        migrations.AlterField(
            model_name="сomment",
            name="text",
            field=models.TextField(verbose_name="Текст комментария"),
        ),
    ]
