# Generated by Django 3.2 on 2023-08-15 19:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0004_auto_20230814_2156'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сomment',
            new_name='Comment',
        ),
    ]
